CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE `adonis_schema` (`id` integer not null primary key autoincrement, `name` varchar(255) not null, `batch` integer not null, `migration_time` datetime default CURRENT_TIMESTAMP);
CREATE TABLE `adonis_schema_versions` (`version` integer, primary key (`version`));
CREATE TABLE `users` (`id` integer not null primary key autoincrement, `first_name` varchar(255) null, `last_name` varchar(255) null, `email` varchar(255) not null, `password` varchar(255) not null, `role_id` integer not null, `created_at` datetime not null, `updated_at` datetime not null, foreign key(`role_id`) references `roles`(`id`) on delete RESTRICT);
CREATE UNIQUE INDEX `users_email_unique` on `users` (`email`);
CREATE TABLE `roles` (`id` integer not null primary key autoincrement, `role_name` varchar(255) not null, `created_at` datetime not null, `updated_at` datetime not null);
CREATE UNIQUE INDEX `roles_role_name_unique` on `roles` (`role_name`);
CREATE TABLE `physical_quantities` (`id` integer not null primary key autoincrement, `quantity_name` varchar(255) not null, `unit_name` varchar(255) not null, `unit_symbol` varchar(255) not null, `created_at` datetime not null, `updated_at` datetime not null);
CREATE UNIQUE INDEX `physical_quantities_quantity_name_unique` on `physical_quantities` (`quantity_name`);
CREATE TABLE `genset_properties` (`id` integer not null primary key autoincrement, `property_name` varchar(255) not null, `quantity_id` integer, `created_at` datetime not null, `updated_at` datetime not null, foreign key(`quantity_id`) references `physical_quantities`(`id`) on delete RESTRICT);
CREATE UNIQUE INDEX `genset_properties_property_name_unique` on `genset_properties` (`property_name`);
CREATE TABLE `archives` (`id` integer not null primary key autoincrement, `timestamp` datetime not null, `property_id` integer not null, `property_value` float not null, `is_anomaly` boolean not null, `created_at` datetime not null, `updated_at` datetime not null, foreign key(`property_id`) references `genset_properties`(`id`) on delete RESTRICT);
CREATE TABLE `notification_types` (`id` integer not null primary key autoincrement, `type` varchar(255) not null, `created_at` datetime not null, `updated_at` datetime not null);
CREATE UNIQUE INDEX `notification_types_type_unique` on `notification_types` (`type`);
CREATE TABLE `notifications` (`id` integer not null primary key autoincrement, `summary` varchar(255) not null, `message` varchar(255) null, `archive_id` integer not null, `should_be_displayed` boolean not null, `notification_type_id` integer not null, `created_at` datetime not null, `updated_at` datetime not null, foreign key(`archive_id`) references `archives`(`id`) on delete RESTRICT, foreign key(`notification_type_id`) references `notification_types`(`id`) on delete RESTRICT);
