// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeNonSerializedTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AuthGithubRedirectGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['githubRedirect'], false>
}
type AuthGithubCallbackGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['githubCallback'], false>
}
type AuthGoogleRedirectGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['googleRedirect'], false>
}
type AuthGoogleCallbackGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['googleCallback'], false>
}
type AuthGetloggedinuserGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['getLoggedInUser'], false>
}
type AuthGetactiveGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['getActive'], false>
}
type AuthGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['getAll'], false>
}
type AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['createUserValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['register'], true>
}
type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], true>
}
type AuthUpdatePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['updateUserProfileValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['update'], true>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type AuthActivateIdPatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['activate'], false>
}
type AuthDeactivateIdPatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['deactivate'], false>
}
type AuthHarddeleteIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['destroy'], false>
}
type RoleGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/role_controller.ts').default['getAll'], false>
}
type RoleCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/role.ts')['createRoleValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/role_controller.ts').default['create'], true>
}
type RoleUpdatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/role.ts')['createRoleValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/role_controller.ts').default['update'], true>
}
type RoleDeleteIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/role_controller.ts').default['delete'], false>
}
type PhysicalquantityGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/physical_quantity_controller.ts').default['getAll'], false>
}
type PhysicalquantityCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/physical_quantity.ts')['createPhysicalQuantityValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/physical_quantity_controller.ts').default['create'], true>
}
type PhysicalquantityUpdateIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/physical_quantity.ts')['updatePhysicalQuantityValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/physical_quantity_controller.ts').default['update'], true>
}
type PhysicalquantityDeleteIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/physical_quantity_controller.ts').default['delete'], false>
}
type PropertyGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/genset_property_controller.ts').default['getAll'], false>
}
type PropertyCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/genset_property.ts')['createGensetPropertyValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/genset_property_controller.ts').default['create'], true>
}
type PropertyUpdateIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/genset_property.ts')['updateGensetPropertyValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/genset_property_controller.ts').default['update'], true>
}
type PropertyDeleteIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/genset_property_controller.ts').default['delete'], false>
}
type ArchiveGetpropertystatisticsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/archive.ts')['getPropertyStatisticsValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getPropertyStatistics'], true>
}
type ArchiveGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getAll'], false>
}
type ArchiveCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/archive.ts')['createArchiveValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['create'], true>
}
type ArchiveDeletePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['delete'], false>
}
type ArchiveGetbetweenGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getBetween'], false>
}
type ArchiveGetlatestGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getLatest'], false>
}
type ArchiveGetpropertydatabetweenPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/archive.ts')['getArchiveDataPropertyBetweenValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getPropertyDataBetween'], true>
}
type ArchiveGetpaginatedPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/archive.ts')['getPaginatedDataValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getPaginated'], true>
}
type ArchiveDeleteallPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['deleteAll'], false>
}
type ArchiveGetanomalystatisticsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/archive.ts')['getAnomalyStatisticsValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/archive_controller.ts').default['getAnomalyStatistics'], true>
}
type NotificationtypeGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_type_controller.ts').default['getAll'], false>
}
type NotificationtypeCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/notification_type.ts')['createNotificationTypeValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_type_controller.ts').default['create'], true>
}
type NotificationtypeUpdateIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/notification_type.ts')['createNotificationTypeValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_type_controller.ts').default['update'], true>
}
type NotificationtypeDeleteIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_type_controller.ts').default['delete'], false>
}
type NotificationGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['getAll'], false>
}
type NotificationGetresolvedGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['getResolved'], false>
}
type NotificationGetunresolvedGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['getUnresolved'], false>
}
type NotificationSummaryGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['summary'], false>
}
type NotificationCountGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['count'], false>
}
type NotificationAnomalystatscountGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['anomalyStatsCount'], false>
}
type NotificationReadIdPatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['read'], false>
}
type NotificationCreateGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/notification.ts')['createNotificationValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['create'], true>
}
type NotificationUpdatePatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['update'], false>
}
type NotificationResolvemultiplePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['resolveMultiple'], false>
}
type NotificationClearPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['clearRecords'], false>
}
type NotificationPaginateGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/notification_controller.ts').default['getAll'], false>
}
type PdmCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/pdm.ts')['createPdmValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['create'], true>
}
type PdmGetrecentGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getRecent'], false>
}
type PdmGetlatestentryGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getLatestEntry'], false>
}
type PdmGetrecentactualGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getRecentActual'], false>
}
type PdmGetrecentforecastedGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getRecentForecasted'], false>
}
type PdmNotificationGetresolvedGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getResolved'], false>
}
type PdmNotificationGetallGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getAllNotifications'], false>
}
type PdmNotificationGetunresolvedGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getUnresolved'], false>
}
type PdmNotificationGetlatestunresolvedGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getLatestUnresolvedNotification'], false>
}
type PdmNotificationReadIdPatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['markNotificationRead'], false>
}
type PdmNotificationGetstatisticsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/pdm.ts')['getPdmStatisticsValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['getStatistics'], true>
}
type PdmNotificationClearPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['clearRecords'], false>
}
type PdmDeleteDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/pdm_controller.ts').default['delete'], false>
}
type MlNotifyloginPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/ml_controller.ts').default['notifyLogin'], false>
}
type ReportsGeneratedummyGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/reports_controller.ts').default['generateDummy'], false>
}
export interface ApiDefinition {
  'auth': {
    'github': {
      'redirect': {
        '$url': {
        };
        '$get': AuthGithubRedirectGetHead;
        '$head': AuthGithubRedirectGetHead;
      };
      'callback': {
        '$url': {
        };
        '$get': AuthGithubCallbackGetHead;
        '$head': AuthGithubCallbackGetHead;
      };
    };
    'google': {
      'redirect': {
        '$url': {
        };
        '$get': AuthGoogleRedirectGetHead;
        '$head': AuthGoogleRedirectGetHead;
      };
      'callback': {
        '$url': {
        };
        '$get': AuthGoogleCallbackGetHead;
        '$head': AuthGoogleCallbackGetHead;
      };
    };
    'getLoggedInUser': {
      '$url': {
      };
      '$get': AuthGetloggedinuserGetHead;
      '$head': AuthGetloggedinuserGetHead;
    };
    'getActive': {
      '$url': {
      };
      '$get': AuthGetactiveGetHead;
      '$head': AuthGetactiveGetHead;
    };
    'getAll': {
      '$url': {
      };
      '$get': AuthGetallGetHead;
      '$head': AuthGetallGetHead;
    };
    'register': {
      '$url': {
      };
      '$post': AuthRegisterPost;
    };
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'update': {
      '$url': {
      };
      '$patch': AuthUpdatePatch;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
    'activate': {
      ':id': {
        '$url': {
        };
        '$patch': AuthActivateIdPatch;
      };
    };
    'deactivate': {
      ':id': {
        '$url': {
        };
        '$patch': AuthDeactivateIdPatch;
      };
    };
    'hardDelete': {
      ':id': {
        '$url': {
        };
        '$delete': AuthHarddeleteIdDelete;
      };
    };
  };
  'role': {
    'getAll': {
      '$url': {
      };
      '$get': RoleGetallGetHead;
      '$head': RoleGetallGetHead;
    };
    'create': {
      '$url': {
      };
      '$post': RoleCreatePost;
    };
    'update': {
      '$url': {
      };
      '$post': RoleUpdatePost;
    };
    'delete': {
      ':id': {
        '$url': {
        };
        '$delete': RoleDeleteIdDelete;
      };
    };
  };
  'physicalQuantity': {
    'getAll': {
      '$url': {
      };
      '$get': PhysicalquantityGetallGetHead;
      '$head': PhysicalquantityGetallGetHead;
    };
    'create': {
      '$url': {
      };
      '$post': PhysicalquantityCreatePost;
    };
    'update': {
      ':id': {
        '$url': {
        };
        '$patch': PhysicalquantityUpdateIdPatch;
      };
    };
    'delete': {
      ':id': {
        '$url': {
        };
        '$delete': PhysicalquantityDeleteIdDelete;
      };
    };
  };
  'property': {
    'getAll': {
      '$url': {
      };
      '$get': PropertyGetallGetHead;
      '$head': PropertyGetallGetHead;
    };
    'create': {
      '$url': {
      };
      '$post': PropertyCreatePost;
    };
    'update': {
      ':id': {
        '$url': {
        };
        '$patch': PropertyUpdateIdPatch;
      };
    };
    'delete': {
      ':id': {
        '$url': {
        };
        '$delete': PropertyDeleteIdDelete;
      };
    };
  };
  'archive': {
    'getPropertyStatistics': {
      '$url': {
      };
      '$get': ArchiveGetpropertystatisticsGetHead;
      '$head': ArchiveGetpropertystatisticsGetHead;
    };
    'getAll': {
      '$url': {
      };
      '$get': ArchiveGetallGetHead;
      '$head': ArchiveGetallGetHead;
    };
    'create': {
      '$url': {
      };
      '$post': ArchiveCreatePost;
    };
    'delete': {
      '$url': {
      };
      '$post': ArchiveDeletePost;
    };
    'getBetween': {
      '$url': {
      };
      '$get': ArchiveGetbetweenGetHead;
      '$head': ArchiveGetbetweenGetHead;
    };
    'getLatest': {
      '$url': {
      };
      '$get': ArchiveGetlatestGetHead;
      '$head': ArchiveGetlatestGetHead;
    };
    'getPropertyDataBetween': {
      '$url': {
      };
      '$post': ArchiveGetpropertydatabetweenPost;
    };
    'getPaginated': {
      '$url': {
      };
      '$post': ArchiveGetpaginatedPost;
    };
    'deleteAll': {
      '$url': {
      };
      '$post': ArchiveDeleteallPost;
    };
    'getAnomalyStatistics': {
      '$url': {
      };
      '$get': ArchiveGetanomalystatisticsGetHead;
      '$head': ArchiveGetanomalystatisticsGetHead;
    };
  };
  'notificationType': {
    'getAll': {
      '$url': {
      };
      '$get': NotificationtypeGetallGetHead;
      '$head': NotificationtypeGetallGetHead;
    };
    'create': {
      '$url': {
      };
      '$post': NotificationtypeCreatePost;
    };
    'update': {
      ':id': {
        '$url': {
        };
        '$patch': NotificationtypeUpdateIdPatch;
      };
    };
    'delete': {
      ':id': {
        '$url': {
        };
        '$delete': NotificationtypeDeleteIdDelete;
      };
    };
  };
  'notification': {
    'getAll': {
      '$url': {
      };
      '$get': NotificationGetallGetHead;
      '$head': NotificationGetallGetHead;
    };
    'getResolved': {
      '$url': {
      };
      '$get': NotificationGetresolvedGetHead;
      '$head': NotificationGetresolvedGetHead;
    };
    'getUnresolved': {
      '$url': {
      };
      '$get': NotificationGetunresolvedGetHead;
      '$head': NotificationGetunresolvedGetHead;
    };
    'summary': {
      '$url': {
      };
      '$get': NotificationSummaryGetHead;
      '$head': NotificationSummaryGetHead;
    };
    'count': {
      '$url': {
      };
      '$get': NotificationCountGetHead;
      '$head': NotificationCountGetHead;
    };
    'anomalyStatsCount': {
      '$url': {
      };
      '$get': NotificationAnomalystatscountGetHead;
      '$head': NotificationAnomalystatscountGetHead;
    };
    'read': {
      ':id': {
        '$url': {
        };
        '$patch': NotificationReadIdPatch;
      };
    };
    'create': {
      '$url': {
      };
      '$get': NotificationCreateGetHead;
      '$head': NotificationCreateGetHead;
    };
    'update': {
      '$url': {
      };
      '$patch': NotificationUpdatePatch;
    };
    'resolveMultiple': {
      '$url': {
      };
      '$post': NotificationResolvemultiplePost;
    };
    'clear': {
      '$url': {
      };
      '$post': NotificationClearPost;
    };
    'paginate': {
      '$url': {
      };
      '$get': NotificationPaginateGetHead;
      '$head': NotificationPaginateGetHead;
    };
  };
  'pdm': {
    'create': {
      '$url': {
      };
      '$post': PdmCreatePost;
    };
    'getRecent': {
      '$url': {
      };
      '$get': PdmGetrecentGetHead;
      '$head': PdmGetrecentGetHead;
    };
    'getLatestEntry': {
      '$url': {
      };
      '$get': PdmGetlatestentryGetHead;
      '$head': PdmGetlatestentryGetHead;
    };
    'getRecentActual': {
      '$url': {
      };
      '$get': PdmGetrecentactualGetHead;
      '$head': PdmGetrecentactualGetHead;
    };
    'getRecentForecasted': {
      '$url': {
      };
      '$get': PdmGetrecentforecastedGetHead;
      '$head': PdmGetrecentforecastedGetHead;
    };
    'notification': {
      'getResolved': {
        '$url': {
        };
        '$get': PdmNotificationGetresolvedGetHead;
        '$head': PdmNotificationGetresolvedGetHead;
      };
      'getAll': {
        '$url': {
        };
        '$get': PdmNotificationGetallGetHead;
        '$head': PdmNotificationGetallGetHead;
      };
      'getUnresolved': {
        '$url': {
        };
        '$get': PdmNotificationGetunresolvedGetHead;
        '$head': PdmNotificationGetunresolvedGetHead;
      };
      'getLatestUnresolved': {
        '$url': {
        };
        '$get': PdmNotificationGetlatestunresolvedGetHead;
        '$head': PdmNotificationGetlatestunresolvedGetHead;
      };
      'read': {
        ':id': {
          '$url': {
          };
          '$patch': PdmNotificationReadIdPatch;
        };
      };
      'getStatistics': {
        '$url': {
        };
        '$post': PdmNotificationGetstatisticsPost;
      };
      'clear': {
        '$url': {
        };
        '$post': PdmNotificationClearPost;
      };
    };
    'delete': {
      '$url': {
      };
      '$delete': PdmDeleteDelete;
    };
  };
  'ml': {
    'notify-login': {
      '$url': {
      };
      '$post': MlNotifyloginPost;
    };
  };
  'reports': {
    'generateDummy': {
      '$url': {
      };
      '$get': ReportsGeneratedummyGetHead;
      '$head': ReportsGeneratedummyGetHead;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
